# Generated by Django 2.2.20 on 2021-04-19 01:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=500)),
                ('brand', models.CharField(max_length=200)),
                ('specifications', models.TextField()),
                ('series_number', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('Good', 'Good'), ('Needs repair', 'Needs repair'), ('In repair', 'In repair')], default='Good', max_length=100)),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_date', models.DateTimeField()),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='equipment.Equipment')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Person')),
            ],
        ),
    ]
